### ISSUE TITLE
R5C,每隔2-3小时就会死机一次，你有这个现象吗

### ISSUE THREAD

**Issue by antbuster** [gngpp/NanoPi-R5C#3]
R5C,每隔2-3小时就会死机一次，你有这个现象吗

**Comment by gngpp** [comment]
> R5C,每隔2-3小时就会死机一次，你有这个现象吗

没有，我跑了两天了

**Comment by gngpp** [comment]
> R5C,每隔2-3小时就会死机一次，你有这个现象吗

建议换电源测试
